version: '3.8'
services:
  angular-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    environment:
      - DEBIAN_FRONTEND=noninteractive
    stdin_open: true
    tty: true
